export const popularCoffee = [
  {
    "id": 1,
    "news": true,
    "title": "Coffee Latte",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4,
    "price": 22.5,
    "amount": 0,
  },
  {
    "id": 2,
    "news": true,
    "title": "Coffee 2",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.1,
    "price": 32.5,
    "amount": 0,
  },
  {
    "id": 3,
    "news": true,
    "title": "Coffee 3",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 3,
    "price": 12.5,
    "amount": 0,
  },
  {
    "id": 4,
    "news": true,
    "title": "Coffee 4",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 1,
    "price": 14.5,
    "amount": 0,
  },
  {
    "id": 5,
    "news": true,
    "title": "Coffee 5",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 2,
    "price": 24.5,
    "amount": 0,
  },
  {
    "id": 6,
    "news": true,
    "title": "Coffee 6",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 60.5,
    "amount": 0,
  },
  {
    "id": 7,
    "news": true,
    "title": "Coffee 7",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 12.5,
    "amount": 0,
  },
  {
    "id": 8,
    "news": true,
    "title": "Coffee Latte",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 12.5,
    "amount": 0,
  },
  {
    "id": 9,
    "news": true,
    "title": "Coffee Latte",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 12.5,
    "amount": 0,
  },
  {
    "id": 10,
    "news": true,
    "title": "Coffee Latte",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 12.5,
    "amount": 0,
  },
  {
    "id": 11,
    "news": true,
    "title": "Coffee Latte",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 12.5,
    "amount": 0,
  },
  {
    "id": 12,
    "news": true,
    "title": "Coffee Latte",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 12.5,
    "amount": 0,
  },
  {
    "id": 13,
    "news": true,
    "title": "Coffee Latte",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 12.5,
    "amount": 0,
  },
  {
    "id": 14,
    "news": true,
    "title": "Coffee Latte",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 12.5,
    "amount": 0,
  },
  {
    "id": 15,
    "news": true,
    "title": "Coffee Latte",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 12.5,
    "amount": 0,
  },
  {
    "id": 16,
    "news": true,
    "title": "Coffee Latte",
    "image": "https://gocoffee.com.br/wp-content/uploads/2019/05/avela-sombra.png",
    "ml": 300,
    "stars": 4.3,
    "price": 12.5,
    "amount": 0,
  }
]